### ISSUE TITLE
Solution Design and Presentation

### ISSUE THREAD

**Issue by weirdyang** [weirdyang/sgsew-project-tracker#3]
Placeholder for issue to track tasks to be done

This is for week 4: Solution Design/Presentation

**Comment by weirdyang** [comment]
## core deliverables

- Functional requirements 
- Project scope and objectives
- Project plan
- Minutes of meeting 
- Software and hardware specifications
- Implementation Schedule (Burn down Chart)

**Comment by weirdyang** [comment]
Additional Deliverables (min. is 4 deliverables)

[] Surveys/Interviews questions and outcomes
[] Primary and Secondary research 
[] Data Visualization
[] Data Preparation 
[] Project architecture
[] Prototype wireframe mock-up
[] Database design
[] Use cases
[] User Guide

**Comment by weirdyang** [comment]
Project architecture:

1. mongoDB database
2. Express API backend
3. Angular frontend

Prototype wireframe mock-up:

1. Mockup of website layout
2. API documentation

 Database design:
 
1. Collection schemas
2. Relationship between collections
3. Validation

Use cases:

1. Create, update and delete products
2. User management
3. Showcase products and services

**Comment by weirdyang** [comment]
Functional Requirements: 

 

User must be able to login securely. 

Authenticated users must be able to enter product creation page

Authenticated users must be able to enter product update page

Authenticated users must be able to edit the products they created.

Authenticated users must have his/her products stored in a database. 

All users must be able to view product entries.

Admin users must be able to modify or remove all product entries.

**Comment by BharethRex** [comment]
![Home - Phone](https://user-images.githubusercontent.com/78330867/128626713-2daa6781-6867-4067-9441-566bcb784f81.jpg)
![Product Service Catalogue -Desktop](https://user-images.githubusercontent.com/78330867/128626714-c7917192-6bc0-4600-8560-c101a369d367.jpg)
![Product Service Catalogue- Phone](https://user-images.githubusercontent.com/78330867/128626715-4120da31-b901-41fb-8fe6-be7f570d44f2.jpg)
![About Us - Desktop](https://user-images.githubusercontent.com/78330867/128626716-305ba3c4-c973-4d6d-8731-95903ad4bc28.jpg)
![About Us - Phone](https://user-images.githubusercontent.com/78330867/128626717-fdee892c-df21-4a00-be5c-3f3fa16f10c2.jpg)
![Home - Desktop](https://user-images.githubusercontent.com/78330867/128626718-5b0f5731-6037-4924-9b91-61c2aa481d64.jpg)

Possible initial designs for the site. Barebones wireframes.

**Comment by BharethRex** [comment]
![Home - Desktop](https://user-images.githubusercontent.com/78330867/128626784-56d64282-a279-4871-9b48-430492e1a3a8.jpg)
![Home - Phone](https://user-images.githubusercontent.com/78330867/128626785-9b9c9b41-ce37-4512-9cf3-99a979bd2b30.jpg)

Possible Designs for Home Pg, barebones wireframes.

**Comment by BharethRex** [comment]
![About Us - Desktop](https://user-images.githubusercontent.com/78330867/128626798-860a8243-9348-42a5-80c7-f5fe79a3886c.jpg)
![About Us - Phone](https://user-images.githubusercontent.com/78330867/128626799-cd1d30c3-8479-4acc-ac5d-a26c95e785e7.jpg)

![image](https://user-images.githubusercontent.com/78330867/128626801-b039b463-4534-4d2c-8b5a-7ad6a3b9acff.png)

Possible Designs for About Us/Contact Us Pg, barebones wireframes.

**Comment by BharethRex** [comment]
![About Us - Desktop](https://user-images.githubusercontent.com/78330867/128626819-b2688541-f34b-413c-bb6d-d3f73bf93a75.jpg)
![About Us - Phone](https://user-images.githubusercontent.com/78330867/128626821-a986584b-0dc8-4a17-abe3-2de3a7d3a5ff.jpg)

Possible Designs for About Us/Contact Us Pg, barebones wireframes.

**Comment by BharethRex** [comment]
![Product Service Catalogue -Desktop](https://user-images.githubusercontent.com/78330867/128626832-ac4e377a-9de7-4adb-a40b-e570931c5a0c.jpg)
![Product Service Catalogue- Phone](https://user-images.githubusercontent.com/78330867/128626834-099ab06e-f230-4486-8976-94ac1ae142a5.jpg)

Possible Design for Products/Services Catalogue Pg, barebones wireframes.

**Comment by BharethRex** [comment]
![Product Service Catalogue -Desktop](https://user-images.githubusercontent.com/78330867/128627473-25c09aa7-8cf9-454a-8022-50b18f30e575.jpg)
![Product Service Catalogue- Phone](https://user-images.githubusercontent.com/78330867/128627475-b1188398-1e16-4387-9d73-f27336592c7f.jpg)

Possible Designs for Product/Service Catalogue Pg, barebones wireframes.

**Comment by weirdyang** [comment]
# project objectives

To create a functional website providing information about the company and its business (e.g. products and services)

To provide a data entry system for the employees to create, read, update and delete product entries.

**Comment by weirdyang** [comment]
# project scope

Develop backend to provide a web api for users to create, read, update and delete products and users

Develop front end web application

Integrate backend with front end web application

**Comment by weirdyang** [comment]
# acceptance criteria:
 
People must able to access the web application.
Authorized users must be able to create and update products.
Authorized users must be able to create an account.
Authorized users must be able to login.
All site visitors must be able to view the company products and services.

**Comment by weirdyang** [comment]
# Functional Requirements:

User must be able to login securely.

Users must be able to create an account.

Only users with the sign up key is able to access the user registration page to create an account.

Authenticated users must be able to enter product creation page

Authenticated users must be able to enter product update page

Authenticated users must be able to edit the products they created.

Authenticated users must have his/her products stored in a database.

All users must be able to view product entries.

All users must be able to search and filter product entries.

Admin users must be able to modify or remove all product entries.

There must be a page providing company details.

There must be a page to allow authenticated users to create product entries

There must be a page to allow to edit the products they created.

There must be a page to allow the admin users to modify and delete user information.

**Comment by weirdyang** [comment]
# use cases

See https://github.com/weirdyang/sgsew-project-tracker/tree/main/documentation/functional-requirement

**Comment by BharethRex** [comment]
> Admin users must be able to modify or remove all product entries.

Admin users must be able to modify or remove all user entries.

**Comment by weirdyang** [comment]
## Software and Hardware Specs

Microsoft Teams and Github as our tool for Collaboration.

Angular Front End and Nodejs Express for backend.

Github for Version Control.

Netlify for cloud resources for front end. Heroku web hosting for cloud resources for backend

MongoAtlas for Mongodb service to store database of users and products

**Comment by weirdyang** [comment]
## Project architecture

TODO: generate design based on software and hardware specs

**Comment by weirdyang** [comment]
# Sitemap

https://github.com/weirdyang/sgsew-project-tracker/blob/main/documentation/sitemap/sitemap.PNG

**Comment by weirdyang** [comment]
# Database design

https://github.com/weirdyang/sgsew-project-tracker/blob/main/documentation/database/database-config.PNG

**Comment by weirdyang** [comment]
# Project plan

TODO: to build gnatt chart

**Comment by weirdyang** [comment]
# Prototypes

https://github.com/weirdyang/sgsew-project-tracker/tree/main/documentation/Initial%20Wireframes

TODO: @weirdyang  to upload screenshots of login, register, product modals

**Comment by weirdyang** [comment]
# Implementation Schedule (Burn down Chart)

TODO: generate based on project plan

**Comment by weirdyang** [comment]
> # Prototypes
> https://github.com/weirdyang/sgsew-project-tracker/tree/main/documentation/Initial%20Wireframes
> 
> TODO: @weirdyang to upload screenshots of login, register, product modals

done

**Comment by weirdyang** [comment]
> ## Project architecture
> TODO: generate design based on software and hardware specs

done

**Comment by weirdyang** [comment]
## future improvements

1 . allow user to reset password and change username and email
2.

**Comment by weirdyang** [comment]
Constraints -
Free versions of cloud hosting services
