### ISSUE TITLE
[feature] Add user roles

### ISSUE THREAD

**Issue by weirdyang** [weirdyang/sgsew-project-tracker#6]
Add users roles: admin and user

Admin users should be able to access an admin page where they can modify other user details

**Comment by BharethRex** [comment]
Add user role: Super Admin

Super Admin User should be able to change/delete all other users when necessary.

**Comment by weirdyang** [comment]
Maybe we can have just 1 super user in the admin role, and this user will be seeded into the database during deployment. i.e. an admin account can only be created by a database transaction.

**Comment by BharethRex** [comment]
> Add user role: Super Admin
> 
> Super Admin User should be able to change/delete all other users when necessary.



> Maybe we can have just 1 super user in the admin role, and this user will be seeded into the database during deployment. i.e. an admin account can only be created by a database transaction.

Ok, to simplify things, only one admin role that can change/delete users will be seeded into the database during deployment.
