### ISSUE TITLE
[epic] user management

### ISSUE THREAD

**Issue by weirdyang** [weirdyang/sgsew-project-tracker#7]
Story(user-management) as an employee I want to be able to create an account so that I can create and update the products.

## acceptance criteria 

users are able to create an account
Users are able to login
Users are able to create products
Users are able to edit the products they created

User properties:
- username - min length 6 chars 
- email - must be valid email 
- role - either admin or normal 
- password - one numeric, one uppercase and one lowercase, min length 8 characters 
- avatar - preset in front end

**Comment by weirdyang** [comment]
theme(user-management) only registered users are able to create, view and edit products

**Comment by weirdyang** [comment]
theme(user-management) users in normal user role can only edit their own products

**Comment by weirdyang** [comment]
theme(user-management) user in admin role are able to delete users

**Comment by weirdyang** [comment]
theme(user-management) user in admin role are able to edit and delete other users products

**Comment by weirdyang** [comment]
theme(user-management) unauthorized users  can only view product cards and not edit them.

**Comment by weirdyang** [comment]
Users are consist of:

•  username - min length 6 chars 
•  email - must be valid email 
•  role - either admin or normal 
•  password - one numeric, one uppercase and one lowercase, min length 8 characters 
•  avatar - preset in front end

**Comment by weirdyang** [comment]
Story(user-management): As a site owner, I want all users to be able to view products page, about page, home page and contact page

## acceptance criteria

All users, authenticated and unauthenticated, are able to view the products, about, home and contact page.

**Comment by weirdyang** [comment]
Story(user-management): As a site owner, I want only authorized users to be able to create an account so that I can control who is allowed to make changes to the product entries.

## acceptance criteria
Only users with a sign up key can access the registration page to create an account

**Comment by BharethRex** [comment]
Story(user-management) As a site owner, I do not want products that are created and linked to former employees (users who have been removed account access) to be removed from the site when their accounts are removed from the system/database.

So that there will be no need to transfer product "ownership" of the product from the former user's account to a new user account.

## acceptance criteria
all products with a `user` foreign key that link products to their creators are not removed when the user account that its linked to is deleted.

**Comment by BharethRex** [comment]
> Story(user-management) as an admin I want user in admin role are able to delete users so that inactive users can be purged from the system.
> 
> ## acceptance criteria
> Only users in admin role can delete users

Story(user-management) As a site owner, I would need a Super Admin account to control the amount of admin role accounts that are created so that admin accounts that no longer have a use can be removed.

## acceptance criteria
Only users in Super Admin role can delete every other user-type.

**Comment by BharethRex** [comment]
> Story(user-management) as an admin I want user in admin role are able to delete users so that inactive users can be purged from the system.
> 
> ## acceptance criteria
> Only users in admin role can delete users

Story(user-management) As a site owner, I would want admin accounts to be not able to remove other admin accounts due to security reasons (one admin can remove the rest of the admins and take over the site)

## acceptance criteria
Admin role accounts cannot delete other admin role accounts (security reason)

**Comment by weirdyang** [comment]
> > Story(user-management) as an admin I want user in admin role are able to delete users so that inactive users can be purged from the system.
> > ## acceptance criteria
> > Only users in admin role can delete users
> 
> Story(user-management) As a site owner, I would need a Super Admin account to control the amount of admin role accounts that are created so that admin accounts that no longer have a use can be removed.
> 
> ## acceptance criteria
> Only users in Super Admin accounts can delete every other user-type.

To simplify things could we just have one admin account, that can only be created through the database directly?

so the admin will on be able to delete and modify user details, but be unable to assign new roles.

**Comment by BharethRex** [comment]
> > > Story(user-management) as an admin I want user in admin role are able to delete users so that inactive users can be purged from the system.
> > > ## acceptance criteria
> > > Only users in admin role can delete users
> > 
> > 
> > Story(user-management) As a site owner, I would need a Super Admin account to control the amount of admin role accounts that are created so that admin accounts that no longer have a use can be removed.
> > ## acceptance criteria
> > Only users in Super Admin accounts can delete every other user-type.
> 
> To simplify things could we just have one admin account, that can only be created through the database directly?
> 
> so the admin will on be able to delete and modify user details, but be unable to assign new roles.

Ok, to simplify things, that would be a better approach. So only 1 admin account which is able to delete users and modify details.
